import mongoose from 'mongoose';


export default {
  products: [
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/d1.jpg',
      price: 60,
      brand: ' Nike',
      description: 'high quality shirt',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/d2.jpg',
      price: 50,
      brand: ' Nike',
      countInStock: 5,
      description: 'medium quality shirt',
      rating: 4.2,
      numReviews: 5
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best T-shirt',
      category: 'Shirts',
      image: '/images/d3.jpg',
      price: 80,
      brand: ' Nike',
      description: 'high quality pants',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/d4.jpg',
      price: 75,
      brand: ' Nike',
      description: 'high quality pants',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/d5.jpg',
      price: 90,
      brand: ' Nike',
      description: 'high quality pants',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Pants',
      category: 'Pants',
      image: '/images/d6.jpg',
      price: 110,      
      brand: ' Nike',
      description: 'high quality pants',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },  
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Bags',
      category: 'Sack Bags',
      image: '/images/d7.jpg',
      price: 50,      
      brand: ' Nike',
      description: 'high quality bags',
      rating: 4.1,
      numReviews: 12,
      countInStock: 6,
    },  
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Bags',
      category: 'Sack Bags',
      image: '/images/d8.jpg',
      price: 140,      
      brand: 'Aba',
      description: 'high quality bags',
      rating: 4.1,
      numReviews: 45,
      countInStock: 0,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Bags',
      category: 'Sack Bags',
      image: '/images/d9.jpg',
      price: 90,      
      brand: ' Aba',
      description: 'high quality bags',
      rating: 4.5,
      numReviews: 32,
      countInStock: 16,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Bags',
      category: 'Hand Bags',
      image: '/images/d10.jpg',
      price: 200,      
      brand: ' Aba',
      description: 'high quality bags',
      rating: 4.8,
      numReviews: 122,
      countInStock: 26,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Bags',
      category: 'Hand Bags',
      image: '/images/d11.jpg',
      price: 150,      
      brand: ' Jos',
      description: 'high quality bags',
      rating: 4.3,
      numReviews: 72,
      countInStock: 19,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Bags',
      category: 'Hand Bags',
      image: '/images/d12.jpg',
      price: 180,      
      brand: ' Jos',
      description: 'high quality bags',
      rating: 4.6,
      numReviews: 92,
      countInStock: 23,
    },  
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Footwear',
      category: 'Sandals',
      image: '/images/d13.jpg',
      price: 80,      
      brand: ' Aba',
      description: 'high quality footwear',
      rating: 4.4,
      numReviews: 52,
      countInStock: 36,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Footwear',
      category: 'Sandals',
      image: '/images/d14.jpg',
      price: 60,      
      brand: ' Lagos',
      description: 'high quality footwear',
      rating: 4.0,
      numReviews: 22,
      countInStock: 12,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Footwear',
      category: 'Sandals',
      image: '/images/d15.jpg',
      price: 120,      
      brand: ' Lagos',
      description: 'high quality footwear',
      rating: 4.7,
      numReviews: 82,
      countInStock: 14,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Belts',
      category: 'Belts',
      image: '/images/d16.jpg',
      price: 40,      
      brand: ' Jos',
      description: 'high quality belt',
      rating: 4.2,
      numReviews: 42,
      countInStock: 26,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Belts',
      category: 'Belts',
      image: '/images/d17.jpg',
      price: 30,      
      brand: 'Aba',
      description: 'high quality belt',
      rating: 4.1,
      numReviews: 32,
      countInStock: 16,
    },
    {
      _id: new mongoose.Types.ObjectId(),
      name: 'Best Belts',
      category: 'Belts',
      image: '/images/d18.jpg',
      price: 50,      
      brand: ' Jos',
      description: 'high quality belt',
      rating: 4.3,
      numReviews: 52,
      countInStock: 2,
    },
  ]
}